# Generated by Django 2.0.7 on 2018-08-01 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180801_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
    ]
