# Generated by Django 2.0.7 on 2018-08-01 18:39

from django.db import migrations, models
import django.db.models.deletion
import recruiter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_auto_20180802_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=70)),
                ('phone_no', models.BigIntegerField(validators=[recruiter.models.validate_phone_number])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='organization.Organization')),
            ],
        ),
    ]
