# Generated by Django 2.0.7 on 2018-08-01 18:13

import applicant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone_no',
            field=models.BigIntegerField(validators=[applicant.models.validate_phone_number]),
        ),
    ]
